version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  registries:
  - git-github-com
